# How to make a release
# Use the following command to create a release:
# - Update version in Cargo.toml
#   version = "X.Y.Z"
# - Merge the PR to master
# - Create a tag with the version number
#   git tag X.Y.Z
# - Push the tag to GitHub
#   git push origin X.Y.Z
# - Go to releases page and edit the draft release
# - Publish the release

name: release

# Only do the release on x.y.z tags.
on:
  push:
    tags:
    - "[0-9]+.[0-9]+.[0-9]+"

# We need this to be able to create releases.
permissions:
  contents: write

jobs:
  # The create-release job runs purely to initialize the GitHub release itself,
  # and names the release after the `x.y.z` tag that was pushed. It's separate
  # from building the release so that we only create the release once.
  create-release:
    name: create-release
    runs-on: ubuntu-latest
    env:
      VERSION: ""
    steps:
      - uses: actions/checkout@v4
      - name: Get the release version from the tag
        if: env.VERSION == ''
        run: echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
      - name: Show the version
        run: |
          echo "version is: $VERSION"
      - name: Check that tag version and Cargo.toml version are the same
        shell: bash
        run: |
          if ! grep -q "version = \"$VERSION\"" Cargo.toml; then
            echo "version does not match Cargo.toml" >&2
            exit 1
          fi      - name: Create GitHub release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create $VERSION --draft --verify-tag --title $VERSION
      - name: Create version.json
        shell: bash
        run: |
          cat <<EOF > version.json
          {
            "version": "${{ env.VERSION }}",
            "windows": "blue_onyx-${{ env.VERSION }}-win.zip",
            "windows_sha256": "blue_onyx-${{ env.VERSION }}-win.zip.sha256",
            "windows_installer": "blue_onyx-${{ env.VERSION }}-installer.exe",
            "windows_installer_sha256": "blue_onyx-${{ env.VERSION }}-installer.exe.sha256",
            "linux": "blue_onyx-${{ env.VERSION }}-linux.zip",
            "linux_sha256": "blue_onyx-${{ env.VERSION }}-linux.zip.sha256"
          }
          EOF
      - name: Upload version.json
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ env.VERSION }} version.json
      - name: Upload install_latest_blue_onyx.ps1
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ env.VERSION }} install_latest_blue_onyx.ps1
    outputs:
      version: ${{ env.VERSION }}

  build:
    name: build
    needs: ['create-release']
    env:
      RUST_BACKTRACE: 1
      ASSET: ""
      ASSET_SUM: ""
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - build: win
          os: windows-latest
          rust: stable
        - build: linux
          os: ubuntu-latest
          rust: stable

    steps:
    - uses: Jimver/cuda-toolkit@v0.2.24
      if: matrix.os == 'ubuntu-latest'
      id: cuda-toolkit
      with:
        cuda: '12.8.0'

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: python -m pip install flatbuffers numpy mypy pytest setuptools wheel onnx protobuf sympy psutil onnxscript

    - name: Build release
      run: cargo build --release
    # Windows-specific: Install cargo-packager and NSIS for installer creation
    - name: Install cargo-packager and NSIS (Windows only)
      if: matrix.os == 'windows-latest'
      shell: bash
      run: |
        cargo install cargo-packager
        # Install NSIS
        choco install nsis -y
        # Add NSIS to PATH for current session
        echo "C:/Program Files (x86)/NSIS" >> $GITHUB_PATH

    - name: Create Windows installer (Windows only)
      if: matrix.os == 'windows-latest'
      shell: bash
      run: |
        # Build the NSIS installer
        cargo packager --release --formats nsis

    - name: Determine release binaries
      shell: bash
      run: |
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          BIN="target/release/blue_onyx.exe target/release/onnxruntime.dll target/release/DirectML.dll target/release/test_blue_onyx.exe target/release/blue_onyx_benchmark.exe target/release/blue_onyx_service.exe"
        else
          BIN="target/release/blue_onyx target/release/libonnxruntime.so target/release/test_blue_onyx target/release/blue_onyx_benchmark"
          # Add CUDA libraries if they exist
          if [ -f "target/release/libonnxruntime_providers_cuda.so" ]; then
            BIN="$BIN target/release/libonnxruntime_providers_cuda.so"
          fi
          if [ -f "target/release/libonnxruntime_providers_shared.so" ]; then
            BIN="$BIN target/release/libonnxruntime_providers_shared.so"
          fi
        fi
        echo "BIN=$BIN" >> $GITHUB_ENV

    - name: Determine archive name
      shell: bash
      run: |
        version="${{ needs.create-release.outputs.version }}"
        echo "ARCHIVE=blue_onyx-$version-${{ matrix.build }}" >> $GITHUB_ENV

    - name: Creating directory for archive
      shell: bash
      run: |
        mkdir -p "$ARCHIVE"/
        cp $BIN "$ARCHIVE"/    - name: Build archive (Windows)
      shell: bash
      if: matrix.os == 'windows-latest'
      run: |
        7z a "$ARCHIVE.zip" "$ARCHIVE"
        certutil -hashfile "$ARCHIVE.zip" SHA256 > "$ARCHIVE.zip.sha256"
        # Also prepare the installer for upload
        cp target/release/blue_onyx_*_x64-setup.exe "blue_onyx-${{ needs.create-release.outputs.version }}-installer.exe"
        certutil -hashfile "blue_onyx-${{ needs.create-release.outputs.version }}-installer.exe" SHA256 > "blue_onyx-${{ needs.create-release.outputs.version }}-installer.exe.sha256"
        echo "ASSET=$ARCHIVE.zip" >> $GITHUB_ENV
        echo "ASSET_SUM=$ARCHIVE.zip.sha256" >> $GITHUB_ENV
        echo "INSTALLER=blue_onyx-${{ needs.create-release.outputs.version }}-installer.exe" >> $GITHUB_ENV
        echo "INSTALLER_SUM=blue_onyx-${{ needs.create-release.outputs.version }}-installer.exe.sha256" >> $GITHUB_ENV

    - name: Build archive (Unix)
      shell: bash
      if: matrix.os != 'windows-latest'
      run: |
        tar czf "$ARCHIVE.tar.gz" "$ARCHIVE"
        shasum -a 256 "$ARCHIVE.tar.gz" > "$ARCHIVE.tar.gz.sha256"
        echo "ASSET=$ARCHIVE.tar.gz" >> $GITHUB_ENV
        echo "ASSET_SUM=$ARCHIVE.tar.gz.sha256" >> $GITHUB_ENV    - name: Upload release archive
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: bash
      run: |
        version="${{ needs.create-release.outputs.version }}"
        gh release upload "$version" ${{ env.ASSET }} ${{ env.ASSET_SUM }}

    - name: Upload Windows installer (Windows only)
      if: matrix.os == 'windows-latest'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: bash
      run: |
        version="${{ needs.create-release.outputs.version }}"
        gh release upload "$version" ${{ env.INSTALLER }} ${{ env.INSTALLER_SUM }}
