# How to make a release
# Use the following command to create a release:
# - Update version in Cargo.toml
#   version = "X.Y.Z"
# - Merge the PR to master
# - Create a tag with the version number
#   git tag X.Y.Z
# - Push the tag to GitHub
#   git push origin X.Y.Z
# - Go to releases page and edit the draft release
# - Publish the release

name: release

# Only do the release on x.y.z tags.
on:
  push:
    tags:
    - "[0-9]+.[0-9]+.[0-9]+"

# We need this to be able to create releases.
permissions:
  contents: write

jobs:
  # The create-release job runs purely to initialize the GitHub release itself,
  # and names the release after the `x.y.z` tag that was pushed. It's separate
  # from building the release so that we only create the release once.
  create-release:
    name: create-release
    runs-on: ubuntu-latest
    env:
      VERSION: ""
    steps:
      - uses: actions/checkout@v4
      - name: Get the release version from the tag
        if: env.VERSION == ''
        run: echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
      - name: Show the version
        run: |
          echo "version is: $VERSION"
      - name: Check that tag version and Cargo.toml version are the same
        shell: bash
        run: |
          if ! grep -q "version = \"$VERSION\"" Cargo.toml; then
            echo "version does not match Cargo.toml" >&2
            exit 1
          fi
      - name: Create GitHub release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create $VERSION --draft --verify-tag --title $VERSION
      - name: Upload install_latest_blue_onyx.ps1
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ env.VERSION }} install_latest_blue_onyx.ps1
    outputs:
      version: ${{ env.VERSION }}

  build-linux:
    name: build-linux
    needs: ['create-release']
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: 1
      VERSION: ${{ needs.create-release.outputs.version }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@6d653acede28d24f02e3cd41383119e8b1b35921 # master
      with:
        toolchain: stable

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: python -m pip install flatbuffers numpy mypy pytest setuptools wheel onnx protobuf sympy psutil onnxscript

    - name: Build release (Linux)
      run: cargo build --release

    - name: Gather release binaries
      shell: bash
      run: |
        BIN="target/release/blue_onyx target/release/libonnxruntime.so target/release/test_blue_onyx target/release/blue_onyx_benchmark"
        echo "BIN=$BIN" >> $GITHUB_ENV

    - name: Determine archive name
      shell: bash
      run: |
        echo "ARCHIVE=blue_onyx-$VERSION-linux" >> $GITHUB_ENV

    - name: Create archive staging directory
      shell: bash
      run: |
        mkdir -p "$ARCHIVE"/
        cp $BIN "$ARCHIVE"/

    - name: Build Linux archive
      shell: bash
      run: |
        tar czf "$ARCHIVE.tar.gz" "$ARCHIVE"
        shasum -a 256 "$ARCHIVE.tar.gz" > "$ARCHIVE.tar.gz.sha256"

    - name: Upload Linux archive to release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: bash
      run: |
        gh release upload "$VERSION" "$ARCHIVE.tar.gz" "$ARCHIVE.tar.gz.sha256"

  build-windows-winml:
    name: build-windows-winml
    needs: ['create-release']
    runs-on: windows-latest
    env:
      RUST_BACKTRACE: 1
      VERSION: ${{ needs.create-release.outputs.version }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@6d653acede28d24f02e3cd41383119e8b1b35921 # master
      with:
        toolchain: stable

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: python -m pip install flatbuffers numpy mypy pytest setuptools wheel onnx protobuf sympy psutil onnxscript

    - name: Build release (WinML)
      run: cargo build --release

    - name: Install cargo-packager and NSIS
      shell: bash
      run: |
        cargo install cargo-packager
        choco install nsis -y
        echo "C:/Program Files (x86)/NSIS" >> $GITHUB_PATH

    - name: Build Windows installer (WinML)
      shell: bash
      run: |
        cargo packager --release --config packager_winml.toml --formats nsis

    - name: Gather release binaries
      shell: bash
      run: |
        BIN="target/release/blue_onyx.exe target/release/test_blue_onyx.exe target/release/blue_onyx_benchmark.exe target/release/blue_onyx_service.exe"
        echo "BIN=$BIN" >> $GITHUB_ENV

    - name: Determine archive name
      shell: bash
      run: |
        echo "ARCHIVE=blue_onyx-$VERSION-win-winml" >> $GITHUB_ENV
        echo "INSTALLER=blue_onyx-$VERSION-installer-winml.exe" >> $GITHUB_ENV

    - name: Create archive staging directory
      shell: bash
      run: |
        mkdir -p "$ARCHIVE"/
        cp $BIN "$ARCHIVE"/

    - name: Build Windows archive
      shell: bash
      run: |
        7z a "$ARCHIVE.zip" "$ARCHIVE"
        certutil -hashfile "$ARCHIVE.zip" SHA256 > "$ARCHIVE.zip.sha256"
        cp target/release/blue_onyx_*_x64-setup.exe "$INSTALLER"
        certutil -hashfile "$INSTALLER" SHA256 > "$INSTALLER.sha256"

    - name: Upload WinML assets to release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: bash
      run: |
        gh release upload "$VERSION" "$ARCHIVE.zip" "$ARCHIVE.zip.sha256" "$INSTALLER" "$INSTALLER.sha256"

  build-windows-onnx:
    name: build-windows-onnx
    needs: ['create-release']
    runs-on: windows-latest
    env:
      RUST_BACKTRACE: 1
      VERSION: ${{ needs.create-release.outputs.version }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@6d653acede28d24f02e3cd41383119e8b1b35921 # master
      with:
        toolchain: stable

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: python -m pip install flatbuffers numpy mypy pytest setuptools wheel onnx protobuf sympy psutil onnxscript

    - name: Build release (ONNX)
      run: cargo build --release --no-default-features

    - name: Install cargo-packager and NSIS
      shell: bash
      run: |
        cargo install cargo-packager
        choco install nsis -y
        echo "C:/Program Files (x86)/NSIS" >> $GITHUB_PATH

    - name: Build Windows installer (ONNX)
      shell: bash
      run: |
        cargo packager --release --config packager.toml --formats nsis

    - name: Gather release binaries
      shell: bash
      run: |
        BIN="target/release/blue_onyx.exe target/release/test_blue_onyx.exe target/release/blue_onyx_benchmark.exe target/release/blue_onyx_service.exe target/release/onnxruntime.dll target/release/DirectML.dll"
        echo "BIN=$BIN" >> $GITHUB_ENV

    - name: Determine archive name
      shell: bash
      run: |
        echo "ARCHIVE=blue_onyx-$VERSION-win-onnx" >> $GITHUB_ENV
        echo "INSTALLER=blue_onyx-$VERSION-installer-onnx.exe" >> $GITHUB_ENV

    - name: Create archive staging directory
      shell: bash
      run: |
        mkdir -p "$ARCHIVE"/
        cp $BIN "$ARCHIVE"/

    - name: Build Windows archive
      shell: bash
      run: |
        7z a "$ARCHIVE.zip" "$ARCHIVE"
        certutil -hashfile "$ARCHIVE.zip" SHA256 > "$ARCHIVE.zip.sha256"
        cp target/release/blue_onyx_*_x64-setup.exe "$INSTALLER"
        certutil -hashfile "$INSTALLER" SHA256 > "$INSTALLER.sha256"

    - name: Upload ONNX assets to release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: bash
      run: |
        gh release upload "$VERSION" "$ARCHIVE.zip" "$ARCHIVE.zip.sha256" "$INSTALLER" "$INSTALLER.sha256"
